from pathlib import Path
import json
import shutil
import sys

import cv2

import logging 
logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger(__name__)


def run_pipeline(img_path: Path):

    # Paths 
    base_dir = Path(__file__).resolve().parent

    OUTPUT_DIR  = base_dir / "output" / f"{img_path.stem}"

    # Remove old output if it exists
    if OUTPUT_DIR.exists():
        shutil.rmtree(OUTPUT_DIR)
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    TABLE_OUTPUT = OUTPUT_DIR / f"table_{img_path.stem}.jpg"
    LABEL_PATH = OUTPUT_DIR / "labels" / f"{img_path.stem}.txt"
    CROPPED_OUTPUT = OUTPUT_DIR / f"cropped_{img_path.stem}.jpg"
    STRUCT_OUTPUT = OUTPUT_DIR / f"struct_{img_path.stem}.jpg"
    EXTRACTED_JSON = OUTPUT_DIR / f"extracted_{img_path.stem}.json"

    # -----------------------------------------------------------------------------
    # Stage 1: Preprocessing
    # -----------------------------------------------------------------------------
    from preprocess import preprocess

    preprocessed_path = preprocess(str(img_path))

    # -----------------------------------------------------------------------------
    # Stage 2: Table Detection and Cropping
    # -----------------------------------------------------------------------------

    from ultralytics import YOLO

    model = YOLO("model.pt")

    # Run inference
    results = model.predict(
        source=preprocessed_path,
        conf=0.8, 
        save_txt=True, 
        project=str(OUTPUT_DIR),
        name=".",
        exist_ok=True)

    results[0].save(str(TABLE_OUTPUT))


    # Crop table based on label. Uses the original image and the label file generated by YOLO.
    # More robust than cropping the saved table image, which can be affected by padding and resizing.
    image = cv2.imread(str(img_path))
    if image is None:
        print(f"Skipped unreadable image: {img_path}")
        sys.exit(1)

    if not LABEL_PATH.exists():
        print(f"Skipped (no label file): {LABEL_PATH}")
        sys.exit(1)

    height, width = image.shape[:2]
    with LABEL_PATH.open("r", encoding="utf-8") as file:
        lines = [line.strip() for line in file if line.strip()]

    table_class_id = 0
    # x padding is greater because sometimes bbox is too tight and cuts off table borders,
    # which can cause issues for structure detection.
    x_padding = 10
    y_padding = 2

    if lines[0]:
        parts = lines[0].split()
        if len(parts) < 5:
            logger.warning(f"Invalid label format in {LABEL_PATH}: {lines[0]}")
            exit(1)

        cls_id = int(float(parts[0]))
        if cls_id != table_class_id:
            logger.warning(f"Invalid class ID in {LABEL_PATH}: {cls_id}")
            exit(1)

        x_center_n, y_center_n, box_width_n, box_height_n = map(float, parts[1:5])

        box_width = box_width_n * width
        box_height = box_height_n * height
        x_center = x_center_n * width
        y_center = y_center_n * height

        x1 = int(round(x_center - box_width / 2))
        y1 = int(round(y_center - box_height / 2))
        x2 = int(round(x_center + box_width / 2))
        y2 = int(round(y_center + box_height / 2))

        x1 -= x_padding
        y1 -= y_padding
        x2 += x_padding
        y2 += y_padding

        x1 = max(0, min(x1, image.shape[1]))
        x2 = max(0, min(x2, image.shape[1]))
        y1 = max(0, min(y1, image.shape[0]))
        y2 = max(0, min(y2, image.shape[0]))
        if x2 <= x1 or y2 <= y1:
            logger.warning(f"Invalid bounding box for {TABLE_OUTPUT}: ({x1}, {y1}, {x2}, {y2})")
            exit(1)

        cropped = image[y1:y2, x1:x2]
        if cropped.size == 0:
            logger.warning(f"Invalid cropped image for {TABLE_OUTPUT}: ({x1}, {y1}, {x2}, {y2})")
            exit(1)

        cv2.imwrite(str(CROPPED_OUTPUT), cropped)
        logger.info(f"Saved: {CROPPED_OUTPUT}")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python inference.py path/to/image.jpg")
        sys.exit(1)

    img_path = Path(sys.argv[1])
    if not img_path.exists():
        print(f"File not found: {img_path}")
        sys.exit(1)

    run_pipeline(img_path)