import type { Metadata } from 'next'
import '@/styles/globals.css'
import { Inter, Nunito } from 'next/font/google'

const nunito = Nunito({
  variable: '--font-nunito',
  weight: 'variable',
  subsets: ['latin'],
})

const inter = Inter({
  variable: '--font-inter',
  weight: 'variable',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${nunito.variable} ${inter.variable} light antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
