import type { Metadata } from 'next'
import '@/styles/globals.css'
import { Inter, Nunito, Reddit_Sans } from 'next/font/google'
import Navigation from '@/features/navigation/components'

const redditSans = Reddit_Sans({
  variable: '--font-reddit',
  weight: 'variable',
  subsets: ['latin'],
})

const nunito = Nunito({
  variable: '--font-nunito',
  weight: 'variable',
  subsets: ['latin'],
})

const inter = Inter({
  variable: '--font-inter',
  weight: 'variable',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${nunito.variable} ${inter.variable} ${redditSans.variable} light text-foreground relative flex min-h-screen flex-col antialiased`}
      >
        <header className='sticky top-0 z-999'>
          <Navigation />
        </header>
        <main className='flex grow flex-col'>{children}</main>
      </body>
    </html>
  )
}
